/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Uploaded Document */
        get: operations["get_uploaded_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Document Chunks */
        post: operations["create_document_chunks_documents__document_id__chunks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Document Embeddings */
        post: operations["create_document_embeddings_documents__document_id__embeddings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Document */
        post: operations["search_document_documents__document_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/quiz/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Document Quiz */
        post: operations["generate_document_quiz_documents__document_id__quiz_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quiz_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz */
        get: operations["get_quiz_quizzes__quiz_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quiz_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Quiz Attempt */
        post: operations["start_quiz_attempt_quizzes__quiz_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz Attempt */
        get: operations["get_quiz_attempt_attempts__attempt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attempt_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Quiz Attempt */
        post: operations["submit_quiz_attempt_attempts__attempt_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttemptAnswerSubmission */
        AttemptAnswerSubmission: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Option Id
             * Format: uuid
             */
            option_id: string;
        };
        /** AttemptInProgressResponse */
        AttemptInProgressResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Title */
            title: string;
            /** Topic */
            topic: string;
            /** Status */
            status: string;
            /** Total Questions */
            total_questions: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Questions */
            questions: components["schemas"]["AttemptQuestionResponse"][];
        };
        /** AttemptOptionResponse */
        AttemptOptionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** Text */
            text: string;
        };
        /** AttemptQuestionResponse */
        AttemptQuestionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: string;
            /** Position */
            position: number;
            /** Options */
            options: components["schemas"]["AttemptOptionResponse"][];
        };
        /** AttemptReviewAnswerResponse */
        AttemptReviewAnswerResponse: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Selected Answer */
            selected_answer: number;
            /** Correct Answer */
            correct_answer: number;
            /** Is Correct */
            is_correct: boolean;
            /** Explanation */
            explanation: string;
            /** Sources */
            sources: components["schemas"]["AttemptSourceResponse"][];
        };
        /** AttemptSourceResponse */
        AttemptSourceResponse: {
            /** Chunk Id */
            chunk_id: string | null;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index: number;
        };
        /** AttemptSubmissionRequest */
        AttemptSubmissionRequest: {
            /** Answers */
            answers: components["schemas"]["AttemptAnswerSubmission"][];
        };
        /** AttemptSubmittedResponse */
        AttemptSubmittedResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Status */
            status: string;
            /** Score */
            score: number;
            /** Total Questions */
            total_questions: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Answers */
            answers: components["schemas"]["AttemptReviewAnswerResponse"][];
        };
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /**
             * File
             * @description Text-based PDF document
             */
            file: string;
        };
        /** DocumentChunkingResponse */
        DocumentChunkingResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Status */
            status: string;
            /** Page Count */
            page_count: number;
            /** Chunk Count */
            chunk_count: number;
        };
        /** DocumentEmbeddingResponse */
        DocumentEmbeddingResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Status */
            status: string;
            /** Chunk Count */
            chunk_count: number;
            /** Embedded Count */
            embedded_count: number;
            /** Model */
            model: string;
            /** Dimensions */
            dimensions: number;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string | null;
            /** File Size */
            file_size: number | null;
            /** Status */
            status: string;
            /** Page Count */
            page_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DocumentSearchRequest */
        DocumentSearchRequest: {
            /** Query */
            query: string;
            /** Top K */
            top_k?: number;
        };
        /** DocumentSearchResponse */
        DocumentSearchResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Query */
            query: string;
            /** Top K */
            top_k: number;
            /** Result Count */
            result_count: number;
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Dimensions */
            embedding_dimensions: number;
            /** Results */
            results: components["schemas"]["DocumentSearchResult"][];
        };
        /** DocumentSearchResult */
        DocumentSearchResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /**
             * Similarity
             * @description Cosine similarity (1 - cosine distance); higher values are more similar.
             */
            similarity: number;
        };
        /** GeneratedQuestion */
        GeneratedQuestion: {
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Correct Answer */
            correct_answer: number;
            /** Explanation */
            explanation: string;
            /** Sources */
            sources: components["schemas"]["GeneratedSource"][];
        };
        /** GeneratedSource */
        GeneratedSource: {
            /** Chunk Id */
            chunk_id: string | null;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QuizGenerationRequest */
        QuizGenerationRequest: {
            /** Topic */
            topic: string;
            /** Question Count */
            question_count?: number;
            /** Top K */
            top_k?: number;
        };
        /** QuizGenerationResponse */
        QuizGenerationResponse: {
            /** Title */
            title: string;
            /** Questions */
            questions: components["schemas"]["GeneratedQuestion"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Topic */
            topic: string;
            /** Status */
            status: string;
        };
        /** QuizResponse */
        QuizResponse: {
            /** Title */
            title: string;
            /** Questions */
            questions: components["schemas"]["GeneratedQuestion"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Topic */
            topic: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_uploaded_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_chunks_documents__document_id__chunks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentChunkingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_embeddings_documents__document_id__embeddings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEmbeddingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_document_documents__document_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_document_quiz_documents__document_id__quiz_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizGenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_quizzes__quiz_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_quiz_attempt_quizzes__quiz_id__attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptInProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_attempt_attempts__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptInProgressResponse"] | components["schemas"]["AttemptSubmittedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_quiz_attempt_attempts__attempt_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptSubmittedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
